export const achievementBadgeSlugOrder = [
  "set-them-up",
  "resourceful-survivor",
  "barely-made-it",
  "poison-what-poison",
  "no-rest-for-the-wicked",
  "against-all-odds",
  "hard-to-kill",
  "still-breathing",
  "environmental-execution",
  "ancient-scholar",
  "first-one-in",
  "pathfinder",
  "trapbreaker",
  "trap-spotter",
  "cartographer",
  "dungeon-delver",
  "dramatic-entrance",
  "oathkeeper",
  "the-perfect-lie",
  "expert-witness",
  "master-detective",
  "truth-seeker",
  "the-face-of-the-party",
  "i-know-a-guy",
  "master-negotiator",
  "silver-tongue",
  "the-real-mvp",
  "blessed-timing",
  "shield-wall",
  "five-in-one",
  "second-wind-savior",
  "guardian-angel",
  "combat-medic",
  "not-today",
  "concentration-champion",
  "dispel-the-disaster",
  "no-slot-wasted",
  "the-floor-is-lava",
  "magic-missile-massacre",
  "spell-saver",
  "perfect-placement",
  "arcane-sniper",
  "big-boom-theory",
  "counterspell-clutch",
  "boss-breaker",
  "clean-sweep",
  "deaths-door-duelist",
  "bloodied-but-unbroken",
  "untouchable",
  "no-mercy-round",
  "return-to-sender",
  "executioners-timing",
  "the-bigger-they-are",
  "overkill",
  "one-hit-wonder",
  "last-one-standing",
  "monster-hunter",
  "dragonbreaker",
  "longshot-legend",
  "the-party-lives",
  "combo-attack",
  "nobody-gets-left-behind",
  "perfect-plan",
  "formation-fighters",
  "chain-reaction",
  "the-assist-king",
  "door-problem-solver",
  "barrelmancer",
  "friendly-fireball",
  "i-meant-to-do-that",
  "critical-clown",
  "the-shopping-episode",
  "goblin-mode",
  "that-was-the-plan",
  "improvised-weapon-enthusiast",
  "chicken-chaser",
  "campaign-veteran",
  "legend-in-the-making",
  "mythic-name",
  "faction-favorite",
  "nemesis-maker",
  "hero-of-the-people",
  "world-shaker",
  "final-blow",
  "full-circle",
  "the-legend-retires",
] as const;

export const achievementBadgeSourceFileBySlug: Partial<Record<(typeof achievementBadgeSlugOrder)[number], string>> = {
  "combo-attack": "Achievements__0025_Combo-Attack.png",
  "nobody-gets-left-behind": "Achievements__0024_Nobody-Gets-Left-Behind.png",
  "perfect-plan": "Achievements__0023_Perfect-Plan.png",
  "formation-fighters": "Achievements__0022_Formation-Fighters.png",
  "chain-reaction": "Achievements__0021_Chain-Reaction.png",
  "the-assist-king": "Achievements__0020_The-Assist-King.png",
  "door-problem-solver": "Achievements__0019_Door-Problem-Solver.png",
  barrelmancer: "Achievements__0018_Barrelmancer.png",
  "friendly-fireball": "Achievements__0017_Friendly-Fireball.png",
  "i-meant-to-do-that": "Achievements__0016_I-Meant-To-Do-That.png",
  "critical-clown": "Achievements__0015_Critical-Clown.png",
  "the-shopping-episode": "Achievements__0014_Shopping-Episode.png",
  "goblin-mode": "Achievements__0013_Goblin-Mode.png",
  "that-was-the-plan": "Achievements__0012_That-Was-the-Plan.png",
  "improvised-weapon-enthusiast": "Achievements__0011_Improvised-Weapon-Enthusiast.png",
  "chicken-chaser": "Achievements__0010_Chicken-Chaser.png",
  "campaign-veteran": "Achievements__0009_Campaign-Veteran.png",
  "legend-in-the-making": "Achievements__0008_Legend-in-the-Making.png",
  "mythic-name": "Achievements__0001_Wanderer.png",
  "faction-favorite": "Achievements__0007_Faction-Favorite.png",
  "nemesis-maker": "Achievements__0005_Nemesis-Maker.png",
  "hero-of-the-people": "Achievements__0004_Hero-of-the-People.png",
  "world-shaker": "Achievements__0003_World-Shaker.png",
  "final-blow": "Achievements__0002_Final-Blow.png",
  "full-circle": "Achievements__0006_Full-Circle.png",
  "the-legend-retires": "Achievements__0000_Legend-Retires.png",
};

export function getAchievementBadgePath(slug: string) {
  return `/uploads/achievement-badges/${slug}.png`;
}

export const achievementBadgePathBySlug = Object.fromEntries(
  achievementBadgeSlugOrder.map((slug) => [slug, getAchievementBadgePath(slug)])
) as Record<string, string>;
