// Sourced from SB_Adventurers_League_Consumables.xlsm.
export const DEFAULT_LEGAL_CONSUMABLE_OPTIONS = [
  "+1 Ammunition",
  "+1 Arrows",
  "+1 Bolts",
  "+1 Sling Bullets",
  "+2 Bolts",
  "Acid Vial",
  "Adamantine Arrows",
  "Alchemist's Fire",
  "Ammunition +1 (Arrow, bone tipped)",
  "Ammunition +1 (Arrow)",
  "Ammunition +2 (Arrow)",
  "Ammunition +2 (Bolt)",
  "Antitoxin",
  "Arrow +1",
  "Arrow +2",
  "Arrow +3",
  "Arrow of Dragon Slaying",
  "Arrow of Fiend Slaying",
  "Arrow of Giant-Slaying",
  "Assassin's Blood Poison",
  "Bag of Beans",
  "Balloon Packs",
  "Basic Poison",
  "Bead of Force",
  "Bead of Nourishment",
  "Bead of Refreshment",
  "Bolt of Blinding",
  "Bolt of Holding",
  "Bolt of Vapors",
  "Bottled Breath",
  "Bottled Lightning",
  "Bullet +1",
  "Bullseye Lantern",
  "Carnival Prizes",
  "Carrion Crawler Poison",
  "Charm of Feather Falling",
  "Charm of Heroism",
  "Charm of Nine Lives",
  "Charm of Restoration",
  "Charm of the Crystal Heart",
  "Charm of the Maimed",
  "Charm of the Sage",
  "Charm of the Swollen Hag",
  "Charm of Treasure Sense",
  "Charm: Seasoul Touched",
  "Charm: Way of the Dragon",
  "Chime of Opening",
  "Chromatic Roses",
  "Clay No-Face's Charm",
  "Clockwork Amulet",
  "Crossbow Bolts",
  "Crossbow Bolts +1",
  "Crossbow Bolts +2",
  "Dancing Monkey Fruit",
  "Deck of Illusions",
  "Deck of Miscellany",
  "Dried Leech",
  "Dried Leech Arrow",
  "Dried Leech Crossbow Bolt",
  "Drow Poison",
  "Dust of Corrosion",
  "Dust of Disappearance",
  "Dust of Dryness",
  "Dust of Sneezing and Choking",
  "Elemental Gem",
  "Elemental Gem (Blue Sapphire)",
  "Elemental Gem (Emerald)",
  "Elemental Gem (Red Corundum)",
  "Elemental Gem (Yellow Diamond)",
  "Elixir of Health",
  "Empty Vials",
  "Essence of Ether Poison",
  "Feather Token (Bird)",
  "Feather Token (Fan)",
  "Feather Token (Feather Fall)",
  "Flask of Oil",
  "Gem of Brightness",
  "Glowrune Pigments",
  "Healer's Kit",
  "Herbalism Kit",
  "Joho's Charm",
  "Keoghtom's Ointment",
  "Mark of Prestige",
  "Menga leaves",
  "Mesmerizing Incense",
  "Midnight tears poison",
  "Mind Crystal (Careful)",
  "Mind Crystal (Distance)",
  "Mind Crystal (Distant)",
  "Mind Crystal (Empowered)",
  "Mind Crystal (Extended)",
  "Mind Crystal (Heightened)",
  "Mind Crystal (Quickened)",
  "Mind Crystal (Subtle)",
  "Mumified Toad",
  "Mummy Dust",
  "Mushrooms and Toadstools",
  "Mystery Key",
  "Necklace of Fireballs",
  "Nolzur's Marvelous Pigments",
  "Oil of Etherealness",
  "Oil of Sharpness",
  "Oil of Slipperiness",
  "Paper Bird",
  "Perfume of Bewitching",
  "Philter of Love",
  "Pixie Dust",
  "Potion of Acid Resistance",
  "Potion of Advantage",
  "Potion of Animal Friendship",
  "Potion of Bottled Breath",
  "Potion of Bubble Breath",
  "Potion of Clairvoyance",
  "Potion of Climbing",
  "Potion of Cloud Giant Strength",
  "Potion of Cold Resistance",
  "Potion of Comprehension",
  "Potion of Dimunition",
  "Potion of Dragon's Majesty",
  "Potion of Fire Breath",
  "Potion of Fire Giant Strength",
  "Potion of Fire Resistance",
  "Potion of Flying",
  "Potion of Force Resistance",
  "Potion of Frost Giant Strength",
  "Potion of Gaseous Form",
  "Potion of Giant Size",
  "Potion of Greater Healing",
  "Potion of Growth",
  "Potion of Healing",
  "Potion of Heroism",
  "Potion of Hill Giant Strength",
  "Potion of Invisibility",
  "Potion of Invulnerability",
  "Potion of Lightning Resistance",
  "Potion of Longevity",
  "Potion of Mind Control (Beast)",
  "Potion of Mind Control (Fire Giant)",
  "Potion of Mind Control (Humanoid)",
  "Potion of Mind Control (monster)",
  "Potion of Mind Reading",
  "Potion of Necrotic Resistance",
  "Potion of Poison",
  "Potion of Poison (appears as Supreme Healing)",
  "Potion of Poison Resistance",
  "Potion of Polymorph",
  "Potion of Possibility",
  "Potion of Psionic Fortitude",
  "Potion of Psychic Resistance",
  "Potion of Pugilism",
  "Potion of Radiant Resistance",
  "Potion of Restful Watch",
  "Potion of Revivify",
  "Potion of Speed",
  "Potion of Stone Giant Strength",
  "Potion of Storm Giant Strength",
  "Potion of Superior Healing",
  "Potion of Supreme Healing",
  "Potion of Thunder Resistance",
  "Potion of Vitality",
  "Potion of Watchful Rest",
  "Potion of Water Breathing",
  "Pressure Capsules",
  "Quaal's Feather Token (Anchor)",
  "Quaal's Feather Token (Bird)",
  "Quall's Feather Token (anchor)",
  "Restorative Ointment",
  "Scatterleaf Tea",
  "Scroll of Alarm",
  "Scroll of animal friendship",
  "Scroll of Animate Dead",
  "Scroll of Arcane Lock",
  "Scroll of Banishment",
  "Scroll of Bestow Curse",
  "Scroll of Bless",
  "Scroll of Blight",
  "Scroll of Burning Hands",
  "Scroll of Catnap",
  "Scroll of Cloudkill",
  "Scroll of Command",
  "Scroll of Commune with Nature",
  "Scroll of Comprehend Languages",
  "Scroll of Confusion",
  "Scroll of Contingency",
  "Scroll of Control Water",
  "Scroll of Create Bonfire",
  "Scroll of Create Undead",
  "Scroll of Cure Wounds (2nd level)",
  "Scroll of Cure Wounds (3rd level)",
  "Scroll of Darkvision",
  "Scroll of Dawn",
  "Scroll of Daylight",
  "Scroll of Death Ward",
  "Scroll of Detect Magic",
  "Scroll of Detect Thoughts",
  "Scroll of Dimension Door",
  "Scroll of Disguise Self",
  "Scroll of Dominate Monster",
  "Scroll of Dominate Person",
  "Scroll of Enhance Ability",
  "Scroll of Fabricate",
  "Scroll of False Life",
  "Scroll of Fear",
  "Scroll of Feather Fall",
  "Scroll of Fireball",
  "Scroll of Fizban's Platinum Shield",
  "Scroll of Flame Strike",
  "Scroll of Fly",
  "Scroll of Freedom of Movement",
  "Scroll of Gaseous Form",
  "Scroll of Grasping Vines",
  "Scroll of Greater Restoration",
  "Scroll of Haste",
  "Scroll of Heroes' Feast",
  "Scroll of Heroism",
  "Scroll of Hold Person",
  "Scroll of Hypnotic Pattern",
  "Scroll of Invisibility",
  "Scroll of Knock",
  "Scroll of Legend Lore",
  "scroll of Leomund's Tiny Hut",
  "Scroll of Lesser Restoration",
  "Scroll of Life Transferrance",
  "Scroll of Lightning Arrow",
  "Scroll of Mass Cure Wounds",
  "Scroll of Mass Healing Word",
  "Scroll of Mass Suggestion",
  "Scroll of Modify Memory",
  "Scroll of Otulke's Resilient Sphere",
  "Scroll of Passwall",
  "Scroll of Plane Shift",
  "Scroll of Polymorph",
  "Scroll of Power Word Pain",
  "Scroll of Prayer of Healing",
  "Scroll of Project Image",
  "Scroll of Protection",
  "Scroll of Protection (Aberration)",
  "Scroll of Protection (Demons)",
  "Scroll of Protection (Elementals)",
  "Scroll of Protection (feline beasts and feline lycanthropes)",
  "Scroll of Protection (Fiends)",
  "Scroll of Protection (from Elementals)",
  "Scroll of Protection (Humanoids)",
  "Scroll of Protection (Lycanthropes)",
  "Scroll of Protection (Plants)",
  "Scroll of Protection (Undead)",
  "Scroll of Protection (Undead) for each character",
  "Scroll of Protection from Evil and Good",
  "Scroll of Protection from Fiends",
  "Scroll of Protection from Good and Evil",
  "Scroll of Protection from Good/Evil",
  "Scroll of Protection from Humanoids",
  "Scroll of Protection from Plants",
  "Scroll of Protection from Poison",
  "Scroll of Protection from Undead",
  "Scroll of Raise Dead",
  "Scroll of Regeneration",
  "Scroll of Remove Curse",
  "Scroll of Resurrection",
  "Scroll of Revivify",
  "Scroll of Sanctuary",
  "Scroll of Sending",
  "Scroll of Shadow Blade",
  "Scroll of Shocking Grasp",
  "Scroll of Silence",
  "Scroll of Speak with Animals",
  "Scroll of Speak with Dead",
  "Scroll of Spike Growth",
  "Scroll of Steel Wind Strike",
  "Scroll of Stone Shape",
  "Scroll of Stoneskin",
  "Scroll of Summon Fey",
  "Scroll of Symbol",
  "Scroll of Synaptic Static",
  "Scroll of Tarrasque Summoning",
  "Scroll of Telekinesis",
  "Scroll of Teleport",
  "Scroll of Teleportation Circle",
  "Scroll of the Comet",
  "Scroll of Thunder Step",
  "Scroll of Tidal Wave",
  "Scroll of Tongues",
  "Scroll of Vampiric Touch",
  "Scroll of Wall of Ice",
  "Scroll of Water Breathing",
  "Scroll of Water Walk",
  "Scroll of Web",
  "Serpent Venom Poison",
  "Silvered Bolts",
  "Silvered Darts",
  "Silvered Sling bullets",
  "Sinda Berries",
  "Sling Bullets +1",
  "Smokepowder",
  "Smokepowder Packet",
  "Soul Coin",
  "Sovereign Glue",
  "Spell Scroll of Absorb Elements",
  "Spell Scroll of Aid",
  "Spell Scroll of Air Bubble",
  "Spell Scroll of Air Bubble (5th level)",
  "Spell Scroll of Alarm",
  "Spell Scroll of Alter Self",
  "Spell Scroll of Animal Friendship",
  "Spell Scroll of Animal Messenger",
  "Spell Scroll of Animate Dead",
  "Spell Scroll of Antagonize",
  "Spell Scroll of Antilife Shell",
  "Spell Scroll of Arms of Hadar",
  "Spell Scroll of Ashardalon's Stride",
  "Spell Scroll of Aura of Purity",
  "Spell Scroll of Aura of Vitality",
  "Spell Scroll of Bane",
  "Spell Scroll of Beacon of Hope",
  "Spell Scroll of Beast Bond",
  "Spell Scroll of Blade Barrier",
  "Spell Scroll of Bless",
  "Spell Scroll of Bless (5th Level)",
  "Spell Scroll of Blight",
  "Spell Scroll of Blindness/Deafness",
  "Spell Scroll of Blink",
  "Spell Scroll of Blur",
  "Spell Scroll of Burning Hands",
  "Spell Scroll of Call Lightning",
  "Spell Scroll of Calm Emotions",
  "Spell Scroll of Catapult",
  "Spell Scroll of Catnap",
  "Spell Scroll of Cause Fear",
  "Spell Scroll of Ceremony",
  "Spell Scroll of Chaos Bolt",
  "Spell Scroll of Chromatic Orb",
  "Spell Scroll of Circle of Power",
  "Spell Scroll of Clairvoyance",
  "Spell Scroll of Cloud of Daggers",
  "Spell Scroll of Color Spray",
  "Spell Scroll of Command",
  "Spell Scroll of Commune",
  "Spell Scroll of Comprehend Languages",
  "Spell Scroll of Cone of Cold",
  "Spell Scroll of Conjure Barrage",
  "Spell Scroll of Conjure Fey Potion of Fire Giant Strength",
  "Spell scroll of contact other plane",
  "Spell Scroll of Continual Flame",
  "Spell Scroll of Control Water",
  "Spell Scroll of Control Winds",
  "Spell Scroll of Cordon of Arrows",
  "Spell Scroll of Counterspell",
  "Spell Scroll of Create Bonfire",
  "Spell Scroll of Create or Destroy Water",
  "Spell Scroll of Create Spelljammer Helm",
  "Spell Scroll of Create Spelljamming Helm",
  "Spell Scroll of Creation",
  "Spell Scroll of Crown of Madness",
  "Spell Scroll of Crusader's Mantle",
  "Spell Scroll of Cure Wounds",
  "Spell Scroll of Danse Macabre",
  "Spell Scroll of Darkvision",
  "Spell Scroll of Dawn",
  "Spell Scroll of Daylight",
  "Spell Scroll of Destructive Wave",
  "Spell Scroll of Detect Evil and Good",
  "Spell Scroll of Detect Magic",
  "Spell Scroll of Detect Thoughts",
  "Spell Scroll of Detext Thoughts",
  "Spell Scroll of Disguise Self",
  "Spell Scroll of Dispel Evil and Good",
  "Spell Scroll of Dispel Magic",
  "Spell Scroll of Dominate Person",
  "Spell Scroll of Drawmij's Instant Summons",
  "Spell Scroll of Dream",
  "Spell Scroll of Druidcraft",
  "Spell Scroll of Elemental Bane",
  "Spell Scroll of Enemies Abound",
  "Spell Scroll of Enhance Ability",
  "Spell Scroll of Enlarge / Reduce",
  "Spell Scroll of Enlarge/Reduce",
  "Spell scroll of entangle",
  "Spell Scroll of Enthrall",
  "Spell Scroll of Erupting Earth",
  "Spell Scroll of Etheralness",
  "Spell Scroll of Expeditious Retreat",
  "Spell Scroll of Fabricate",
  "Spell Scroll of Faerie Fire",
  "Spell Scroll of False Life",
  "Spell Scroll of Far Step",
  "Spell Scroll of Fear",
  "Spell Scroll of Feather Fall",
  "Spell Scroll of Feign Death",
  "Spell Scroll of Find Familiar",
  "Spell Scroll of Fireball",
  "Spell Scroll of Flame Strike",
  "Spell Scroll of Flesh to Stone",
  "Spell Scroll of Fly",
  "Spell Scroll of Fog Cloud",
  "Spell Scroll of Forbiddance",
  "Spell Scroll of Fount of Moonlight",
  "Spell Scroll of Freedom of Movement",
  "Spell Scroll of Frost Finger",
  "Spell Scroll of Frost Fingers",
  "Spell Scroll of Gaseous Form",
  "Spell Scroll of Gate Seal",
  "Spell Scroll of Geas",
  "Spell Scroll of Gentle Repose",
  "Spell Scroll of Glyph of Warding",
  "Spell Scroll of Goodberry",
  "Spell Scroll of Grease",
  "Spell Scroll of Greater Invisibility",
  "Spell Scroll of Greater Restoration",
  "Spell Scroll of Guardian of Nature",
  "Spell Scroll of Guards and Wards",
  "Spell Scroll of Guidance",
  "Spell Scroll of Hallow",
  "Spell Scroll of Hallucinatory Terrain",
  "Spell Scroll of Haste",
  "Spell Scroll of Heal",
  "Spell Scroll of Healing Spirit",
  "Spell Scroll of Heat Metal",
  "Spell Scroll of Heroism",
  "Spell Scroll of Hold Monster",
  "Spell Scroll of Hold Person",
  "Spell Scroll of Holy Weapon",
  "Spell Scroll of Hypnotic Pattern",
  "Spell Scroll of Ice Knife",
  "Spell Scroll of Identify",
  "Spell Scroll of Illusory Dragon",
  "Spell Scroll of Immolation",
  "Spell Scroll of Incendiary Cloud",
  "Spell Scroll of Inflict Wounds",
  "Spell Scroll of Intellect Fortress",
  "Spell Scroll of Investiture of Stone",
  "Spell Scroll of Investiture of Wind",
  "Spell Scroll of Invisibility",
  "Spell Scroll of Jallarzi's Storm",
  "Spell Scroll of Knock",
  "Spell Scroll of Leeomund's Tiny Hut",
  "Spell scroll of legend lore",
  "Spell Scroll of Leomund's Tiny Hut",
  "Spell Scroll of Lesser Restoration",
  "Spell Scroll of Levitate",
  "Spell scroll of Light",
  "Spell Scroll of Lightning Bolt",
  "Spell Scroll of Locate Animals or Plants",
  "Spell Scroll of Locate Creature",
  "Spell Scroll of Locate Object",
  "Spell Scroll of Longstrider",
  "Spell Scroll of Maddening Darkness",
  "Spell Scroll of Maelstrom",
  "Spell Scroll of Mage Armor",
  "Spell Scroll of Mage Hand",
  "Spell Scroll of Magic Circle",
  "Spell Scroll of Magic Missile",
  "Spell Scroll of Magic Stone",
  "Spell Scroll of Magic Weapon",
  "Spell Scroll of Major Image",
  "Spell Scroll of Mass Cure Wounds",
  "Spell Scroll of Mass Healing Word",
  "Spell Scroll of Maximilian's Earthen Grasp",
  "Spell Scroll of Meld Into Stone",
  "Spell Scroll of Mending",
  "Spell Scroll of Mind Blank",
  "Spell Scroll of Mind Spike",
  "Spell Scroll of Misty Step",
  "Spell Scroll of Moonbeam",
  "Spell Scroll of Mordenkainen's Faithful Hound",
  "Spell Scroll of Nathair's Mischief",
  "Spell Scroll of Nathair's Mishief",
  "Spell Scroll of Nondetection",
  "Spell Scroll of Nystul's Magic Aura",
  "Spell Scroll of Pass Without Trace",
  "Spell Scroll of Planar Binding",
  "Spell Scroll of Plane Shift",
  "Spell Scroll of Plant Growth",
  "Spell Scroll of Polymorph",
  "Spell Scroll of Power Word: Pain",
  "Spell Scroll of Prayer of Healing",
  "Spell Scroll of Prestidigitation",
  "Spell Scroll of Primordial Ward",
  "Spell Scroll of Produce Flame",
  "Spell Scroll of Protection Evil Good",
  "Spell Scroll of Protection from Energy",
  "Spell Scroll of Protection from Evil and Good",
  "Spell Scroll of Protection from Poison",
  "Spell Scroll of Raise Dead",
  "Spell Scroll of Rary's Telepathic Bond",
  "Spell Scroll of Raulothim's Psychic Lance",
  "Spell Scroll of Reincarnate",
  "Spell Scroll of Remove Curse",
  "Spell Scroll of Revivify",
  "Spell Scroll of Rime's Binding Ice",
  "Spell Scroll of Rope Trick",
  "Spell Scroll of Sanctuary",
  "Spell Scroll of Scorching Ray",
  "Spell Scroll of Scrying",
  "Spell scroll of See Invisibility",
  "Spell Scroll of Sending",
  "Spell Scroll of Shadow Blade",
  "Spell Scroll of Shield of Faith",
  "Spell Scroll of Sickening Radiance",
  "Spell Scroll of Silence",
  "Spell Scroll of Silent Image",
  "Spell Scroll of Simulacrum",
  "Spell Scroll of Skill Empowerment",
  "Spell Scroll of Sleep",
  "Spell Scroll of Sleet Storm",
  "Spell Scroll of Slow",
  "Spell Scroll of Snare",
  "Spell Scroll of Snilloc's Snowball Storm",
  "Spell Scroll of Snilloc's Snowball Swarm",
  "Spell Scroll of Spare the Dying",
  "Spell Scroll of Speak with Animals",
  "Spell Scroll of Speak with Dead",
  "Spell Scroll of Speak with Plants",
  "Spell Scroll of Spider Climb",
  "Spell Scroll of Spirit Guardians",
  "Spell Scroll of Spray of Cards",
  "Spell Scroll of Stinking Cloud",
  "Spell Scroll of Stoneskin",
  "Spell Scroll of Summon Aberration",
  "Spell Scroll of Summon Beast",
  "Spell Scroll of Summon Celestial",
  "Spell Scroll of Summon Draconic Spirit",
  "Spell Scroll of Summon Elemental",
  "Spell Scroll of Summon Fey",
  "Spell Scroll of Summon Lesser Demons",
  "Spell Scroll of Summon Shadowspawn",
  "Spell Scroll of Summon Undead",
  "Spell Scroll of Sunbeam",
  "Spell Scroll of Tasha's Caustic Brew",
  "Spell Scroll of Tasha's Hideous Laughter",
  "Spell Scroll of Telekinesis",
  "Spell Scroll of Teleport",
  "Spell Scroll of Teleportation Circle",
  "Spell Scroll of Tenser's Floating Disk",
  "Spell Scroll of Thunder Step",
  "Spell Scroll of Tiny Servant",
  "Spell Scroll of Tongues",
  "Spell Scroll of Tree Stride",
  "Spell Scroll of Wall of Fire",
  "Spell Scroll of Wall of Force",
  "Spell Scroll of Warding Bond",
  "Spell Scroll of Warp Sense",
  "Spell Scroll of Water Breathing",
  "Spell Scroll of Water Walk",
  "Spell Scroll of Web",
  "Spell Scroll of Wish",
  "Spell Scroll of Wrath of Nature",
  "Spell Scroll of Yolande's Regal Presence",
  "Spell Scroll of Zone of Truth",
  "Spellwrought Tattoo of Absorb Elements",
  "Spellwrought Tattoo of Air Bubble",
  "Spellwrought Tattoo of Animal Friendship",
  "Spellwrought Tattoo of Antagonize",
  "Spellwrought Tattoo of Ashardalon's Stride",
  "Spellwrought Tattoo of Aura of Vitality",
  "Spellwrought Tattoo of Beacon of Hope",
  "Spellwrought Tattoo of Bestow Curse",
  "Spellwrought Tattoo of Bless",
  "Spellwrought Tattoo of Call Lightning",
  "Spellwrought Tattoo of Cantrip",
  "Spellwrought Tattoo of Catnap",
  "Spellwrought Tattoo of Charm Person",
  "Spellwrought Tattoo of Circle of Power",
  "Spellwrought Tattoo of Clairvoyance",
  "Spellwrought Tattoo of Comprehend Languages",
  "Spellwrought Tattoo of Conjure Minor Elementals",
  "Spellwrought Tattoo of Counterspell",
  "Spellwrought Tattoo of Create Spelljamming Helm",
  "Spellwrought Tattoo of Cure Wounds",
  "Spellwrought Tattoo of Darkness",
  "Spellwrought Tattoo of Darkvision",
  "Spellwrought Tattoo of Death Ward",
  "Spellwrought Tattoo of Dispel Evil and Good",
  "Spellwrought Tattoo of Dispel Magic",
  "Spellwrought Tattoo of Dragon's Breath",
  "Spellwrought Tattoo of Druidcraft",
  "Spellwrought Tattoo of Eldritch Blast",
  "Spellwrought Tattoo of Enhance Ability",
  "Spellwrought Tattoo of Far Step",
  "Spellwrought Tattoo of Feather Fall",
  "Spellwrought Tattoo of Featherfall",
  "Spellwrought Tattoo of Find Familiar",
  "Spellwrought Tattoo of Find Greater Steed",
  "Spellwrought Tattoo of Find Steed",
  "Spellwrought Tattoo of Fireball",
  "Spellwrought Tattoo of Gaseous Form",
  "Spellwrought Tattoo of Greater Restoration",
  "Spellwrought Tattoo of Green-Flame Blade",
  "Spellwrought Tattoo of Guidance",
  "Spellwrought Tattoo of Gust",
  "Spellwrought Tattoo of Hallow OR Spell Scroll of Hallow",
  "Spellwrought Tattoo of Haste",
  "Spellwrought Tattoo of Heroism",
  "Spellwrought Tattoo of Holy Weapon",
  "Spellwrought Tattoo of Hunter's Mark",
  "Spellwrought Tattoo of Intellect Fortress",
  "Spellwrought Tattoo of Jump",
  "Spellwrought Tattoo of Legend Lore",
  "Spellwrought Tattoo of Leomund's Tiny Hut",
  "Spellwrought Tattoo of Lesser Restoration",
  "Spellwrought Tattoo of Light",
  "Spellwrought Tattoo of Lightning Bolt",
  "Spellwrought Tattoo of Locate Creature",
  "Spellwrought Tattoo of Mage Hand",
  "Spellwrought Tattoo of Mass Cure Wounds",
  "Spellwrought Tattoo of Mending",
  "Spellwrought Tattoo of Message",
  "Spellwrought Tattoo of Misty Step",
  "Spellwrought Tattoo of Nathair's Mischief",
  "Spellwrought Tattoo of Pass without Trace",
  "Spellwrought Tattoo of Phantom Steed",
  "Spellwrought Tattoo of Prestidigitation",
  "Spellwrought Tattoo of Raise Dead",
  "Spellwrought Tattoo of Reincarnate",
  "Spellwrought Tattoo of Remove Curse",
  "Spellwrought Tattoo of Revivify",
  "Spellwrought Tattoo of Sacred Flame",
  "Spellwrought Tattoo of Sanctuary",
  "Spellwrought Tattoo of Searing Smite",
  "Spellwrought Tattoo of See Invisibility",
  "Spellwrought Tattoo of Shadow of Moil",
  "Spellwrought Tattoo of Shield",
  "Spellwrought Tattoo of Shield of Faith",
  "Spellwrought Tattoo of Skill Empowerment",
  "Spellwrought Tattoo of Speak with Animals",
  "Spellwrought Tattoo of Speak with Dead",
  "Spellwrought Tattoo of Speak with Plants",
  "Spellwrought Tattoo of Spirit Guardians",
  "Spellwrought Tattoo of Steel Wind Strike",
  "Spellwrought Tattoo of Summon Celestial",
  "Spellwrought Tattoo of Summon Draconic Spirit",
  "Spellwrought Tattoo of Summon Fey",
  "Spellwrought Tattoo of Sword Burst",
  "Spellwrought Tattoo of Synaptic Static",
  "Spellwrought Tattoo of Teleportation Circle",
  "Spellwrought Tattoo of Thunder Step",
  "Spellwrought Tattoo of Warding Bond",
  "Spellwrought Tattoo of Water Walk",
  "Spellwrought Tattoo of Yolande's Regal Presence",
  "Spellwrought Tattoo of Zephyr Strike",
  "Sycamore seeds",
  "Tinderbox",
  "Torpor Poison",
  "Vial of Acid",
  "Vial of Holy Water",
  "Vial of Midnight Tears",
  "Vial of Poison",
  "Walloping Ammunition (Arrow)",
  "Walloping Ammunition (Bolt)",
  "Walloping Ammunition (Bullet)",
  "Walloping Ammunition (Sling Bullet)",
  "Winged Arrow",
  "Winged Crossbow Bolts",
  "Wukka Nuts",
  "Wyvern Poison",
] as const;
