export const DEFAULT_LEGAL_MAGIC_ITEM_OPTIONS = {
  "Common": [
    "Armor of Gleaming",
    "Boots of False Tracks",
    "Candle of the Deep",
    "Cast-Off Armor",
    "Cast-Off Armor, Breastplate",
    "Cast-Off Armor, Plate",
    "Cast-Off Armor, Studded Leather",
    "Charlatan's Die",
    "Chest of Preserving",
    "Cloak of Billowing",
    "Cloak of Many Fashions",
    "Clockwork Amulet",
    "Clothes of Mending",
    "Dark Shard Amulet",
    "Dread Helm",
    "Ear Horn of Hearing",
    "Enduring Spellbook",
    "Ersatz Eye",
    "Flurried Furs",
    "Hat of Vermin",
    "Hat of Wizardry",
    "Heward's Handy Spice Pouch",
    "Horn of Silent Alarm",
    "Illuminator's Tattoo",
    "Instrument of Illusions",
    "Instrument of Scribing",
    "Lantern of Tracking",
    "Lock of Trickery",
    "Masquerade Tattoo",
    "Moon-Touched Sword",
    "Moon-Touched Sword, Rapier",
    "Mystery Key",
    "Orb of Direction",
    "Orb of Gonging",
    "Orb of Time",
    "Perfume of Bewitching",
    "Pipe of Remembrance",
    "Pipe of Smoke Monsters",
    "Pole of Angling",
    "Pole of Collapsing",
    "Pot of Awakening",
    "Prosthetic Limb",
    "Rope of Mending",
    "Ruby of the War Mage",
    "Sekolahian Worshiping Statuette",
    "Shield of Expression",
    "Smoldering Armor",
    "Smoldering Armor, Breastplate",
    "Smoldering Armor, Plate",
    "Smoldering Armor, Scale Mail",
    "Smoldering Armor, Studded Leather",
    "Spellwrought Tattoo, Cantrip",
    "Staff of Adornment",
    "Staff of Birdcalls",
    "Staff of Flowers",
    "Talking Doll",
    "Tankard of Plenty",
    "Tankard of Sobriety",
    "Thermal Cube",
    "Unbreakable Arrow",
    "Veteran's Cane",
    "Wand of Conducting",
    "Wand of Pyrotechnics",
    "Wand of Smiles",
  ],
  "Uncommon": [
    "+1 All-Purpose Tool",
    "+1 Arcane Grimoire",
    "+1 Moon Sickle",
    "+1 Rod of the Pact Keeper",
    "+1 Shield",
    "+1 Wand of the War Mage",
    "+1 Weapon, Battleaxe",
    "+1 Weapon, Club",
    "+1 Weapon, Dagger",
    "+1 Weapon, Flail",
    "+1 Weapon, Glaive",
    "+1 Weapon, Greataxe",
    "+1 Weapon, Greatclub",
    "+1 Weapon, Greatsword",
    "+1 Weapon, Halberd",
    "+1 Weapon, Hand crossbow",
    "+1 Weapon, Handaxe",
    "+1 Weapon, Lance",
    "+1 Weapon, Longbow",
    "+1 Weapon, Longsword",
    "+1 Weapon, Mace",
    "+1 Weapon, Maul",
    "+1 Weapon, Pike",
    "+1 Weapon, Quarterstaff",
    "+1 Weapon, Rapier",
    "+1 Weapon, Scimitar",
    "+1 Weapon, Shortbow",
    "+1 Weapon, Shortsword",
    "+1 Weapon, Sickle",
    "+1 Weapon, Sling",
    "+1 Weapon, Spear",
    "+1 Weapon, Staff",
    "+1 Weapon, Trident",
    "+1 Weapon, War Pick",
    "+1 Weapon, Warhammer",
    "+1 Weapon, Yklwa",
    "Adamantine Chain mail",
    "Adamantine Chain shirt",
    "Adamantine Half-Plate",
    "Adamantine Plate",
    "Adamantine Splint",
    "Alchemy Jug",
    "Amulet of Proof Against Detection and Location",
    "Bag of Holding",
    "Bag of Tricks",
    "Bag of Tricks, Gray",
    "Bag of Tricks, Rust",
    "Balance of Harmony",
    "Balloon Pack",
    "Blood Spear",
    "Bob",
    "Boots of Elvenkind",
    "Boots of Striding and Springing",
    "Boots of the Winterlands",
    "Bracers of Archery",
    "Brooch of Shielding",
    "Broom of Flying",
    "Cap of Water Breathing",
    "Circlet of Blasting",
    "Cloak of Elvenkind",
    "Cloak of Protection",
    "Cloak of the Manta Ray",
    "Coiling Grasp Tattoo",
    "Conch Shell of Leomund's Tiny Hut",
    "Cursed Luckstone",
    "Decanter of Endless Water",
    "Deck of Illusions",
    "Driftglobe",
    "Dust of Disappearance",
    "Dust of Dryness",
    "Eldritch Claw Tattoo",
    "Emerald Pen",
    "Eversmoking Bottle",
    "Eyes of Charming",
    "Eyes of Minute Seeing",
    "Eyes of the Eagle",
    "Feywild Shard",
    "Gauntlets of Ogre Power",
    "Gem of Brightness",
    "Gloves of Missile Snaring",
    "Gloves of Swimming and Climbing",
    "Gloves of Thievery",
    "Goggles of Night",
    "Guardian Emblem",
    "Hat of Disguise",
    "Headband of Intellect",
    "Hellfire Weapon, Greatsword",
    "Hellfire Weapon, Javelin",
    "Hellfire Weapon, Warhammer",
    "Helm of Comprehending Languages",
    "Helm of Telepathy",
    "Helm of Underwater Action",
    "Immovable Rod",
    "Insignia of Claws",
    "Instrument of the Bards, Doss Lute",
    "Instrument of the Bards, Fochlucan Bandore",
    "Instrument of the Bards, Mac-Fuirmidh Cittern",
    "Javelin of Lightning",
    "Keoghtom's Ointment",
    "Lantern of Revealing",
    "Mariner's Armor",
    "Mariner's Armor, Breastplate",
    "Mariner's Armor, Scale Mail",
    "Mariner's Armor, Studded Leather",
    "Mask of the Beast",
    "Medallion of Thoughts",
    "Mithral Armor",
    "Mithral Armor, Breastplate",
    "Mithral Armor, Chain Mail",
    "Mithral Armor, Half-Plate",
    "Mithral Armor, Plate",
    "Mithral Armor, Scale Mail",
    "Mithral Armor, Splint",
    "Nature's Mantle",
    "Necklace of Adaptation",
    "Night Caller",
    "Orc Stone",
    "Paper Bird",
    "Pearl of Power",
    "Periapt of Health",
    "Periapt of Wound Closure",
    "Pipes of Haunting",
    "Pipes of the Sewers",
    "Piwafwi",
    "Propeller Helm",
    "Quiver of Ehlonna",
    "Ring of Jumping",
    "Ring of Mind Shielding",
    "Ring of Swimming",
    "Ring of Truth Telling",
    "Ring of Warmth",
    "Ring of Water Walking",
    "Robe of Serpents",
    "Robe of Useful Items",
    "Rope of Climbing",
    "Saddle of the Cavalier",
    "Seeker Dart",
    "Sending Stones",
    "Sentinel Shield",
    "Serpent Scale Armor",
    "Slippers of Spider Climbing",
    "Staff of the Adder",
    "Staff of the Python",
    "Stone of Good Luck",
    "Stone of Ill Luck",
    "Sword of Vengeance",
    "Sword of Vengeance, Longsword",
    "Trident of Fish Command",
    "Wand of Entangle",
    "Wand of Magic Detection",
    "Wand of Magic Missiles",
    "Wand of Secrets",
    "Wand of Web",
    "Weapon of Warning",
    "Weapon of Warning, Club",
    "Weapon of Warning, Glaive",
    "Weapon of Warning, Greatclub",
    "Weapon of Warning, Greatsword",
    "Weapon of Warning, Javelin",
    "Weapon of Warning, Longbow",
    "Weapon of Warning, Longsword",
    "Weapon of Warning, Net",
    "Weapon of Warning, Scimitar",
    "Weapon of Warning, Spear",
    "Weapon of Warning, Trident",
    "Weapon of Warning, Whip",
    "Weapon of Warning, Yklwa",
    "Wildspace Orrery",
    "Wind Fan",
    "Winged Boots",
    "Wingwear",
  ],
  "Rare": [
    "+1 Armor, Breastplate",
    "+1 Armor, Chain Mail",
    "+1 Armor, Half-Plate",
    "+1 Armor, Leather",
    "+1 Armor, Plate",
    "+1 Armor, Scale Mail",
    "+1 Armor, Splint",
    "+1 Armor, Studded Leather",
    "+2 Amulet of the Devout",
    "+2 Bloodwell Vial",
    "+2 Dragonhide Belt",
    "+2 Moon Sickle",
    "+2 Rhythm-Maker's Drum",
    "+2 Rod of the Pact Keeper",
    "+2 Shield",
    "+2 Wand of the War Mage",
    "+2 Weapon, Battleaxe",
    "+2 Weapon, Dagger",
    "+2 Weapon, Glaive",
    "+2 Weapon, Greataxe",
    "+2 Weapon, Greatsword",
    "+2 Weapon, Hand crossbow",
    "+2 Weapon, Heavy Crossbow",
    "+2 Weapon, Longbow",
    "+2 Weapon, Longsword",
    "+2 Weapon, Mace",
    "+2 Weapon, Maul",
    "+2 Weapon, Morningstar",
    "+2 Weapon, Pike",
    "+2 Weapon, Quarterstaff",
    "+2 Weapon, Rapier",
    "+2 Weapon, Scimitar",
    "+2 Weapon, Shortsword",
    "+2 Weapon, Sickle",
    "+2 Weapon, Spear",
    "+2 Weapon, Staff",
    "+2 Weapon, Trident",
    "+2 Weapon, War Pick",
    "+2 Weapon, Warhammer",
    "+2 Weapon, Whip",
    "Amulet of Health",
    "Amulet of Protection from Turning",
    "Armor of Vulnerability",
    "Arrow-catching Shield",
    "Astromancy Archive",
    "Atlas of Endless Horizons",
    "Badge of the Watch",
    "Bag of Beans",
    "Banner of the Krig Rune",
    "Bead of Force",
    "Bell Branch",
    "Belt of Dwarvenkind",
    "Belt of Hill Giant Strength",
    "Berserker Axe",
    "Blod Stone",
    "Boots of Levitation",
    "Boots of Speed",
    "Bowl of Commanding Water Elementals",
    "Bracer of Flying Daggers",
    "Bracers of Defense",
    "Brazier of Commanding Fire Elementals",
    "Cape of the Mountebank",
    "Cauldron of Plenty",
    "Censer of Controlling Air Elementals",
    "Charm of Plant Command",
    "Chime of Opening",
    "Claw of the Wyrm Rune",
    "Claws of the Umber Hulk",
    "Cloak of Displacement",
    "Cloak of the Bat",
    "Crystal Blade, Rapier",
    "Crystal Blade, Scimitar",
    "Cube of Force",
    "Daern's Instant Fortress",
    "Dagger of Blindsight",
    "Dagger of Venom",
    "Devotee's Censer",
    "Dimensional Shackles",
    "Dodecahedron of Doom",
    "Dragon Slayer",
    "Dragon Slayer, Greatsword",
    "Dragon Slayer, Shortsword",
    "Dragon Wing Bow, Generic",
    "Dragon Wing Bow, Longbow",
    "Dragontooth Dagger",
    "Duplicitous Manuscript",
    "Eagle Whistle",
    "Elemental Essence Shard, Generic",
    "Elven Chain",
    "Far Realm Shard",
    "Feather of Diatryma Summoning",
    "Figurine of Wondrous Power, Bronze Griffon",
    "Figurine of Wondrous Power, Ebony Fly",
    "Figurine of Wondrous Power, Golden Lions",
    "Figurine of Wondrous Power, Ivory Goats",
    "Figurine of Wondrous Power, Marble Elephant",
    "Figurine of Wondrous Power, Onyx Dog",
    "Figurine of Wondrous Power, Serpentine Owl",
    "Flame Tongue",
    "Flame Tongue, Greatsword",
    "Flame Tongue, Longsword",
    "Flame Tongue, Scimitar",
    "Flame Tongue, Shortsword",
    "Folding Boat",
    "Fulminating Treatise",
    "Galder's Bubble Pipe",
    "Gambler's Blade",
    "Gauntlets of Flaming Fury",
    "Gavel of the Venn Rune",
    "Gem of Seeing",
    "Ghost Lantern",
    "Giant Slayer",
    "Giant Slayer, Greatsword",
    "Giant Slayer, Rapier",
    "Glamoured Studded Leather",
    "Gulthias Staff",
    "Hell Hound Cloak",
    "Helm of Teleportation",
    "Heward's Handy Haversack",
    "Hook of Fisher's Delight",
    "Horn of Blasting",
    "Horn of the Endless Maze",
    "Horn of Valhalla, Brass",
    "Horn of Valhalla, Silver",
    "Horseshoes of Speed",
    "Instrument of the Bards, Canaith Mandolin",
    "Instrument of the Bards, Cli Lyre",
    "Ioun Stone, Awareness",
    "Ioun Stone, Protection",
    "Ioun Stone, Reserve",
    "Ioun Stone, Sustenance",
    "Iron Bands of Bilarro",
    "Knave's Eye Patch",
    "Leather Golem Armor",
    "Loadstone",
    "Mace of Disruption",
    "Mace of Smiting",
    "Mace of Terror",
    "Macuahuitl",
    "Mantle of Spell Resistance",
    "Mirror of the Past",
    "Necklace of Fireballs",
    "Necklace of Prayer Beads",
    "Opal of the Ild Rune",
    "Orb of the Stein Rune",
    "Periapt of Proof Against Poison",
    "Portable Hole",
    "Professor Orb",
    "Psi Crystal",
    "Quaal's Feather Token",
    "Ring of Animal Influence",
    "Ring of Evasion",
    "Ring of Feather Falling",
    "Ring of Free Action",
    "Ring of Protection",
    "Ring of Resistance, Acid",
    "Ring of Resistance, Cold",
    "Ring of Resistance, Fire",
    "Ring of Resistance, Force",
    "Ring of Resistance, Lightning",
    "Ring of Resistance, Poison",
    "Ring of Spell Storing",
    "Ring of the Ram",
    "Ring of X-ray Vision",
    "Robe of Eyes",
    "Robe of Summer",
    "Rod of Rulership",
    "Rod of the Vonindod",
    "Rope of Entanglement",
    "Saint Markovia's Thighbone",
    "Scissors of Shadow Snipping",
    "Scorpion Armor",
    "Serpent's Fang",
    "Shadowfell Brand Tattoo",
    "Shield of Missile Attraction",
    "Snurre's Cape",
    "Spelljamming Helm",
    "Spider Staff",
    "Staff of Charming",
    "Staff of Defense",
    "Staff of Healing",
    "Staff of Swarming Insects",
    "Staff of the Woodlands",
    "Staff of Withering",
    "Stone of Controlling Earth Elementals",
    "Stonespeaker Crystal",
    "Sun Blade",
    "Sword of Life Stealing, Rapier",
    "Sword of Life Stealing, Scimitar",
    "Sword of Wounding",
    "Sword of Wounding, Shortsword",
    "Tentacle Rod",
    "Treebane",
    "Vicious Weapon, Glaive",
    "Vicious Weapon, Longbow",
    "Vicious Weapon, Longsword",
    "Vicious Weapon, Mace",
    "Vicious Weapon, Scimitar",
    "Vicious Weapon, Trident",
    "Wand of Binding",
    "Wand of Fear",
    "Wand of Fireballs",
    "Wand of Lightning Bolts",
    "Wand of Paralysis",
    "Wand of Viscid Globs",
    "Wand of Winter",
    "Wand of Wonder",
    "Weird Tank",
    "Wings of Flying",
    "Witchweed",
    "Woodcutter's Axe",
  ],
  "Very Rare": [
    "+2 Armor, Breastplate",
    "+2 Armor, Half-Plate",
    "+2 Armor, Leather",
    "+2 Armor, Plate",
    "+2 Armor, Studded Leather",
    "+3 All-Purpose Tool",
    "+3 Amulet of the Devout",
    "+3 Arcane Grimoire",
    "+3 Bloodwell Vial",
    "+3 Dragonhide Belt",
    "+3 Moon Sickle",
    "+3 Rod of the Pact Keeper",
    "+3 Shield",
    "+3 Wand of the War Mage",
    "+3 Weapon, Battleaxe",
    "+3 Weapon, Dagger",
    "+3 Weapon, Glaive",
    "+3 Weapon, Greatsword",
    "+3 Weapon, Hand crossbow",
    "+3 Weapon, Lance",
    "+3 Weapon, Longsword",
    "+3 Weapon, Pike",
    "+3 Weapon, Quarterstaff",
    "+3 Weapon, Scimitar",
    "+3 Weapon, Sickle",
    "Abracadabrus",
    "Absorbing Tattoo, Generic",
    "Amethyst Lodestone",
    "Amulet of the Black Skull",
    "Amulet of the Planes",
    "Ancient Relic Red Dragon's Thighbone",
    "Animated Shield",
    "Bag of Devouring",
    "Battle Standard of Infernal Power",
    "Belt of Fire Giant Strength",
    "Belt of Stone Giant Strength",
    "Blade of the Medusa",
    "Bobbing Lily Pad",
    "Bracelet of Rock Magic",
    "Candle of Invocation",
    "Carpet of Flying",
    "Cauldron of Rebirth",
    "Cloak of Arachnida",
    "Crystal Ball",
    "Crystalline Chronicle",
    "Dancing Sword",
    "Dancing Sword, Longsword",
    "Dancing Sword, Rapier",
    "Demon Armor",
    "Devastation Orb, Generic",
    "Dragon Scale Mail, Red",
    "Dragon Scale Mail, Silver",
    "Dragon Scale Mail, White",
    "Dwarven Plate",
    "Dwarven Thrower",
    "Efreeti Bottle",
    "Eldritch Staff",
    "Figurine of Wondrous Power, Obsidian Steed",
    "Fish Suit",
    "Frost Brand",
    "Frost Brand, Greatsword",
    "Frost Brand, Longsword",
    "Frost Brand, Rapier",
    "Ghost Step Tattoo",
    "Heartstone",
    "Helm of Brilliance",
    "Helm of Devil Command",
    "Horn of Valhalla, Bronze",
    "Horned Ring",
    "Ingot of the Skold Rune",
    "Instrument of the Bards, Anstruth Harp",
    "Ioun Stone, Absorption",
    "Ioun Stone, Fortitude",
    "Ioun Stone, Insight",
    "Ioun Stone, Intellect",
    "Ioun Stone, Leadership",
    "Ioun Stone, Vitality",
    "Kyrzin's Ooze",
    "Lifewell Tattoo",
    "Lost Sword",
    "Maddgoth's Helm",
    "Manual of Bodily Health",
    "Manual of Gainful Exercise",
    "Manual of Golems",
    "Manual of Quickness of Action",
    "Mirror of Life Trapping",
    "Nine Lives Stealer",
    "Nine Lives Stealer, Longsword",
    "Nine Lives Stealer, Scimitar",
    "Nolzur's Marvelous Pigments",
    "Oathbow",
    "Ornithopter of Flying",
    "Pennant of the Vind Rune",
    "Ring of Regeneration",
    "Ring of Shooting Stars",
    "Ring of Telekinesis",
    "Robe of Scintillating Colors",
    "Robe of Stars",
    "Rod of Absorption",
    "Rod of Alertness",
    "Rod of Security",
    "Sapphire Buckler",
    "Scimitar of Speed",
    "Shard of the Ise Rune",
    "Shield of the Uven Rune",
    "Soul Bag",
    "Spear of Backbiting",
    "Spellguard Shield",
    "Staff of Fate",
    "Staff of Fire",
    "Staff of Frost",
    "Staff of Power",
    "Staff of Striking",
    "Staff of Thunder and Lightning",
    "Steel",
    "Stonky's Ring",
    "Sword of Sharpness",
    "Sword of Sharpness, Greatsword",
    "Tome of Clear Thought",
    "Tome of Leadership and Influence",
    "Tome of Understanding",
    "Wand of Polymorph",
    "Watchful Helm",
    "Whisper",
  ],
  "Legendary": [
    "+3 Armor, Scale Mail",
    "Apparatus of Kwalish",
    "Ascendant Dragon-Touched Focus",
    "Belt of Storm Giant Strength",
    "Black Crystal Tablet",
    "Blackrazor",
    "Blood Fury Tattoo",
    "Cloak of Invisibility",
    "Crystal Ball of True Seeing",
    "Cubic Gate",
    "Defender",
    "Defender, Greatsword",
    "Efreeti Chain",
    "Eye of Xxiphu",
    "Gurt's Greataxe",
    "Hammock of Worlds",
    "Hammock of Worlds, Lesser",
    "Helm of the Scavenger",
    "Holy Avenger",
    "Holy Avenger, Rapier",
    "Ioun Stone, Mastery",
    "Ioun Stone, Regeneration",
    "Luck Blade",
    "Matalotok",
    "Orcsplitter",
    "Plate Armor of Etherealness",
    "Ring of Invisibility",
    "Robe of the Archmagi",
    "Rod of Lordly Might",
    "Rod of Resurrection",
    "Ruby Weave Gem",
    "Scarab of Protection",
    "Staff of the Magi",
    "Talisman of Pure Good",
    "Talisman of the Sphere",
    "Tome of the Stilled Tongue",
    "Vorpal Sword",
    "Vorpal Sword, Scimitar",
    "Wave",
    "Whelm",
    "Ythryn Mythallar",
  ],
  "Unique / Artifacts": [
    "Blade of Avernus",
    "Draakhorn",
    "Bullseye Lantern Skull",
    "Clockwork Dog",
    "Codicil of White",
    "Dagger of Guitar Solos",
    "Draconic Longsword",
    "Dragongleam",
    "Falkir's Helm of Pigheadedness",
    "Gravenhollow Compass Ring",
    "Green Copper Ewer",
    "Hag Eye",
    "Iron Ball",
    "Jade Serpent Staff",
    "Pearl of Undead Detection",
    "Radiance",
    "Shield of Shouting",
    "The Codicil of White",
    "Tloques' Berserker Axe",
  ],
} as const;
